# Base configs
baseurl: "https://pozecata.github.io/photography/"
#baseurl: "" # Comment the above line and uncomment this to test the website locally
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "UA-46465113-2"

# UI configs
title: "Photography by Tudorascu Catalin"
subtitle: "Portfolio of an amateur."
author: "Tudorascu Catalin"
header:
 title: "Photography"
 subtitle: "by Tudorascu Catalin"
footer:
 name: "Buna, eu sunt Cata"
 bio: "Fotograf amator de evenimente, portrete, peisaje, imobiliare și altele.

Pentru detalii si intrebari: "
web_design: "AJ"
# Configure which exif data to display
# Tag is the actual exif tag, icon is a fontawesome icon. Use JSON notation without line breaks
exif: '[{"tag": "Model", "icon": "camera-retro"}, {"tag": "FNumber", "icon": "dot-circle-o"}, {"tag": "ExposureTime", "icon": "clock-o"}, {"tag": "ISOSpeedRatings", "icon": "info-circle"}]'
social_urls:
  instagram: "https://www.instagram.com/pozecata"
  telegram: "0773855091"
